### ISSUE TITLE
Broken version `2.1.1`: bump to cpptrace 0.7.2

### ISSUE THREAD

**Issue by steinwurf-sofie** [jeremy-rifkin/libassert#105]
The new version of libassert `2.1.1` is broken on MacOS and older versions of Ubuntu. Look to bump the cpptrace dependency to include the fix for https://github.com/jeremy-rifkin/cpptrace/issues/174 to solve this.

**Comment by steinwurf-sofie** [comment]
The exact fix is https://github.com/jeremy-rifkin/cpptrace/commit/54a3e6fdf7837c44d20436c77d3469f4524bf6a1, but no `0.7.2` of cpptrace has yet to be created to pull this in. Could open a further issue in cpptrace if wanted.

**Comment by jeremy-rifkin** [comment]
Thanks for opening this, I haven't had a chance to look into this yet. I should be able to tomorrow or Friday.

Another fix for anyone running into issues would be to use a newer version of cmake (with recognition that that's not always as easy as an `apt install` etc).

**Comment by steinwurf-sofie** [comment]
No worries. Just opened an issue to track its progress. Take it when you have time :+1:

**Comment by jeremy-rifkin** [comment]
Now handled in dev, will aim to do a release soon

**Comment by jeremy-rifkin** [comment]
2.1.2 is released with the fix
