### ISSUE TITLE
Resharper and Assertion with message

### ISSUE THREAD

**Issue by DNKpp** [jeremy-rifkin/libassert#106]
Hey,
I recently started using your library. As I often write template code, I didn't notify that issue immediately.
But after a while, when I switched writing an actual class, I always saw red underlining, when using any assert like macro with a message param.
Without a message I do not see any errors.
E.g.
![image](https://github.com/user-attachments/assets/b5a963b6-2202-4f08-a8ee-7cf5ea82eabe)

The code compiles fine, but resharper shows a very weird preview of the macro:
![image](https://github.com/user-attachments/assets/1ac381d1-a356-45c5-9590-91786bea93cc)

I'm by no means a macro expert and have no idea what could cause that issue. Perhaps you have an idea how help resharper out a bit?
I'm working on Windows 11 with Visual Studio 2022 (latest) and the latest resharper installed.

Greetings
Dominic

**Comment by DNKpp** [comment]
Well, I actually found the solution by accident.
I added another dependency, which does the following:
![image](https://github.com/user-attachments/assets/834b7996-417c-4290-9bb7-67fb32c63eb5)

This seems to please resharper, even if it doesn't change anything in regards of compilation proceedure.

**Comment by jeremy-rifkin** [comment]
Hello! Glad you found a solution, I would have been at a loss. Microsoft's legacy preprocessor is not compliant with the language standard. Libassert checks for this and uses a different set of macros in that case, but it looks like resharper internally expects a normal preprocessor.
