### ISSUE TITLE
[Suggestion] Would be nice to have align release of cpptrace and libassert

### ISSUE THREAD

**Issue by redradist** [jeremy-rifkin/libassert#110]
When I use `cpptrace` and `libassert`, `libassert` depends on old version of `cpptrace` and usially I cannot use `libassert` with upstream `cpptrace`

Would. be nice to update version of `libassert` whenever new `cpptrace` is released.

In my workflow I use both libraries from `conan-center`

**Comment by jeremy-rifkin** [comment]
Thanks for opening this, agreed. I think the main issue is the use of the `<cpptrace/basic.hpp>` header. I'll add a guard for that in the next libassert release.

**Comment by jeremy-rifkin** [comment]
Added a fallback in 1bf749d9311d28003d604764aee646c33045c76a

**Comment by jeremy-rifkin** [comment]
2.1.3 is released
