### ISSUE TITLE
Define to disallow return values

### ISSUE THREAD

**Issue by SK83RJOSH** [jeremy-rifkin/libassert#13]
I love this library as it mirrors some assert libraries I've seen in games; but one area of contention I foresee is return values. In many languages it's intentional to disallow this due to the desire to prevent asserts from becoming a part of control flow due to them being completely compiled out in release builds.

Personally I like this feature, but it leads me to wonder if you do anything to ensure a call ends up being no-opped if the return value is unused? In some cases this may be impossible due to side effects, so I wonder if it would be a good idea to allow completely disabling this for those who want to ensure debug logic doesn't accidentally end up included in release builds.

Feel free to correct me if I'm wrong about how this works though! 🙂

**Comment by jeremy-rifkin** [comment]
Thanks for your thoughts! This has been on my mind. So for assert calls* (and verify too) we do rely on the optimizer eliding things if the return value is unused, which should happen under most circumstances (and LTO may be needed sometimes). Aside from returning a value there's another reason we end up relying on the compiler eliding computations from the expression and that is trying to give the optimizer hints. Clang and MSVC have `__builtin_assume` and `__assume` respectively which won't compute side effects for expressions but in GCC the canonical way to do this `if(!expression) { __builtin_unreachable(); }`, and side effects of `expression` can't be avoided here even when unused (demo https://godbolt.org/z/o41M1TW6d).

For runtime checks where there's a side effect that is really undesirable to have in the final build this library provides `CHECK`, which returns* void and doesn't generate any code at all no matter the condition in release.

The philosophy here ends up being something like

- `CHECK`: Nothing at all makes it to the final build
- `ASSERT`: Only side effects and what's needed for a used return value makes it into build
- `VERIFY`: Expression is evaluated and checked in the final build

I'm not opposed to an option to ensure side effects aren't emitted in release from `ASSERT`. It could be helpful to prevent accidental side effects in a build, this does end up being a little nuanced (potentially requiring inspecting the assembly on a tool like Compiler Explorer). It would require disabling return values and disabling optimizer hints for GCC (and restructuring how the hints are done, at the moment everything is done with the if-unreachable pattern even in Clang/MSVC). It would also require some code duplication but not an unreasonable amount.

Pardon the wall of text with no definitive conclusion! TL:DR, complicated design decisions. I'd be interested to hear your further thoughts.

*I pretend these are functions but they are of course macros masquerading themselves as functions

**Comment by SK83RJOSH** [comment]
>Clang and MSVC have __builtin_assume and __assume respectively which won't compute side effects for expressions but in GCC the canonical way to do this if(!expression) { __builtin_unreachable(); }, and side effects of expression can't be avoided here even when unused

This was some very interesting information that I may use in the future; thanks for sharing!

It's unfortunate that the behavior in GCC is the way it is, though I'm very pleased with how well these hints work elsewhere. This brings up another point however, does this mean that all code being used in ASSERT (side effect free or not) must be valid in release? Is this the same for CHECK?

The [MSDN docs](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/assert-asserte-assert-expr-macros?view=msvc-170) mention `When _DEBUG isn't defined, calls to these macros are removed during preprocessing` which I believe to be a good justification for having some sort of short circuit via a define for those who would like to preserve the more "canonical" functionality of asserts in C/C++ (as I, and many others, may be unaware that code may be generated, and that it must be valid in all configurations after years of using built-ins); though by the sounds of it it may not be as simple as a few `((void)0)` macro bodies in release and wrapping of functions as I initially thought.

I think though that this is the main use of such a define, in games and security critical software, a lot of code that you may depend on for assertions and checks should not have any possibility of making it into the final executable lest you leak important implementation details; and so without this there's an increase to the likelihood of that happening if my assumption here is correct (validity in all configs). 🙂 

>Pardon the wall of text with no definitive conclusion! TL:DR, complicated design decisions. I'd be interested to hear your further thoughts.

Not a problem! I appreciate walls of text more than the average person for sure. Hopefully these thoughts of mine are useful to you. 👍

**Comment by jeremy-rifkin** [comment]
`CHECK` expressions don't have to be valid in `NDEBUG` but `ASSERT` expressions do at the moment, yeah. I think I'm in agreement that it would be good to be able to optionally provide more traditional behavior for anyone who wants to use this as more of a drop-in replacement for things like assert.h.

**Comment by SK83RJOSH** [comment]
> `CHECK` expressions don't have to be valid in `NDEBUG` but `ASSERT` expressions do at the moment, yeah. I think I'm in agreement that it would be good to be able to optionally provide more traditional behavior for anyone who wants to use this as more of a drop-in replacement for things like assert.h.

Very well could be that I also need to just get used to `CHECK` to be honest haha. It's a bit weird for me coming from a lot of WINAPI programming where VERIFY=ASSERT, and ASSERT=CHECK. I won't rattle on much more, but I'd be happy to see this land or the documentation to outline these library specifics a bit more clearly. Appreciate you taking the time to hear me out 😊

**Comment by jeremy-rifkin** [comment]
That has definitely been another concern, the three are rather synonymous. Naming things is hard. Maybe it'd be good to make them something along the lines of `ASSERT`, `DEBUG_ASSERT`, `RELEASE_ASSERT`. I'm gunning for a v1.0 release here but I will give this some more thought before making such a release.

**Comment by jeremy-rifkin** [comment]
Alrighty, I have both reworked a lot of the naming here and also implemented this feature to allow this library to be used as more of a drop-in replacement for <cassert>. Thanks for the suggestion!
