### ISSUE TITLE
Possible improvement to assert dialogues on Windows

### ISSUE THREAD

**Issue by SK83RJOSH** [jeremy-rifkin/libassert#14]
Hey there! One thing that occured to me after testing this last night, is that similar libraries I've used in the past skip abort and use [_CrtDbgReport](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/crtdbgreport-crtdbgreportw?view=msvc-170) to display a more user friendly dialogue to users when an assert is encountered. This is primarily useful for debug builds where you have non-technical users who will likely screenshot the dialogue box and forget to include logs; but it's also very useful as a programmer to see the assert details at a glance in the dialogue instead of needing to alt-tab to the logs (eg/ this is the assert I'm debugging right now).

Is this something that you might consider adding? My only concern would be define/macro leakage from the required header, but perhaps the call to abort could be moved to the implementation to get around this?

**Comment by jeremy-rifkin** [comment]
We can definitely do this, thanks for sharing this function! This would go in the .cpp so no worries with leaking macros or bloating compile time or anything. I think the way to go here will be adding an `asserts::config::` option to opt into `_CrtDbgReport` on windows.

**Comment by jeremy-rifkin** [comment]
I tried to implement this and what I found is `_CrtDbgReport` requires a debug CRT and this leads to a lot of linkage complications. Any project using libassert would need to build with `/MTd` or `/MDd` even in release because it would have to match what the library was built with. Unless I'm doing something wrong on the linker end of things.

I think for now this may need to be relegated to custom assertion failure handlers.

What I can do is add the interface that would allow an assertion handler to get information about file name, line number, and function name.

Implementation would look like:

```cpp
void custom_fail(asserts::assert_type type, ASSERTION fatal, const asserts::assertion_printer& printer) {
    std::string message = printer(asserts::utility::terminal_width(STDERR_FILENO));
    if (isatty(STDERR_FILENO)) {
        std::cerr << message << std::endl;
    }
    else {
        std::cerr << asserts::utility::strip_colors(message) << std::endl;
    }
    using asserts::assert_type;
    if (fatal == ASSERTION::FATAL) {
        switch (type) {
            case assert_type::assertion: {
                #if _DEBUG
                 const auto [filename, line, function, assert_message] = printer.get_assertion_info();
                 _CrtDbgReport(_CRT_ASSERT, filename, line, nullptr,
                                                  "%s", asserts::utility::strip_colors(message).c_str());
                #else
                 abort();
                #endif
            }
            break;
            case assert_type::verify:
                throw asserts::verification_failure();
            case assert_type::check:
                throw asserts::check_failure();
            default:
                std::cerr << "unknown assertion type" << std::endl;
                abort();
        }
    }
}
```

**Comment by SK83RJOSH** [comment]
I'm more than happy with that, thanks for taking a look 🤘

**Comment by jeremy-rifkin** [comment]
Thanks, closing for now
