### ISSUE TITLE
Errors with GCC 12.1

### ISSUE THREAD

**Issue by qdewaghe** [jeremy-rifkin/libassert#24]
I started getting  the following error after upgrading my gcc:
```
error: invalid use of ‘auto’
```

By expending the macro I managed to get more context:
```
error: invalid use of ‘auto’

libassert_decomposer.compl expression_decomposer();
~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
```

Replacing 
```
auto libassert_decomposer = libassert::detail::expression_decomposer(libassert ::detail ::expression_decomposer{} << [...] );
```

with 

```
decltype(libassert::detail::expression_decomposer(libassert ::detail ::expression_decomposer{} << [...] )) libassert_decomposer = libassert::detail::expression_decomposer(libassert ::detail ::expression_decomposer{} << [...] );
```
fixes the issue. `[...]` being the expression I'm testing, pretty sure it's irrelevant. Maybe a GCC bug?

**Comment by jeremy-rifkin** [comment]
Thanks so much for the report, that's surprising to me. If it's a bug that's too bad but good to know the workaround is simple (won't be the first workaround for a compiler bug in this library 😅).

What version of GCC are you on? Any chance I can look at a minimal reproducible example on https://godbolt.org?

**Comment by qdewaghe** [comment]
As mentioned in the title, the issue came up with GCC 12.1. `VERIFY(true);` is enough to trigger the issue.

I'm not sure how to have access to libassert on godbolt? It does not seem to be in the library list.

Maybe my distribution scuffed my GCC 🤷 probably need a repro to confirm the issue

**Comment by jeremy-rifkin** [comment]
Ope I missed the title my bad :P 

Not in the library list (yet at least), but the header at least can be included via URL https://godbolt.org/z/xP3xzheTe. I cannot reproduce the issue though, which is most surprising. I suspect gremlins!

**Comment by qdewaghe** [comment]
Ah, I didn't know you could do that with godbolt, that's useful.

The bug is slightly more complicated then I thought.  Here's a minimal example https://godbolt.org/z/4z8GE83Tn

**Comment by jeremy-rifkin** [comment]
Wow this seems to be a very intricate bug. I've submitted a bug report for this here https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105734. 

I would really rather not do the whole `decltype(repeat everything)` but gcc support is of course most important. I will take a more in-depth look at the workaround / any other potential workarounds tomorrow.

**Comment by jeremy-rifkin** [comment]
ahg no that was a revert!

needed to revert because the decltype workaround breaks if the expression is a lambda https://godbolt.org/z/8nYsqc5Ke

**Comment by jeremy-rifkin** [comment]
Alright, the workaround should be good to go. I'd like to add tests for this but I don't think I can easily get gcc 12.1 in github actions. Does this fix look good on your end?

**Comment by qdewaghe** [comment]
Works fine now. Thank you for taking the time to investigate further and report the bug to GCC. :+1:
