### ISSUE TITLE
Strings that contains back slashes display wrongly

### ISSUE THREAD

**Issue by huangqinjin** [jeremy-rifkin/libassert#31]
```cpp
#include "assert.hpp"

int main()
{
    const char* path = "\\hello\\test\\";
    ASSERT(0, "", path);
}
```

![image](https://user-images.githubusercontent.com/8402260/185756884-ab9ea308-47ce-4ff4-8c90-c365db3fa4d3.png)

**Comment by jeremy-rifkin** [comment]
Thank you for the report, looks like it's something to do with how the string is split across multiple lines
![image](https://user-images.githubusercontent.com/51220084/186294846-fde55657-00b8-4ffa-9d94-452ddd8bfa20.png)
![image](https://user-images.githubusercontent.com/51220084/186295143-00a8037d-b73a-40b1-9a36-a60ae09269e6.png)

**Comment by jeremy-rifkin** [comment]
ah https://github.com/jeremy-rifkin/libassert/blob/080b08cb5c9ea4272e9f017ec79c81ca109a2766/src/assert.cpp#L1339-L1340

**Comment by jeremy-rifkin** [comment]
Fixed now, sorry for the slow response!
