### ISSUE TITLE
Could `libassert.hpp` theoretically be user-modified to work with C23?

### ISSUE THREAD

**Issue by GavinRay97** [jeremy-rifkin/libassert#38]
Just curious if this is possible, and how much effort it would take if so. 
I might give it a shot if it's in the 2-8 hour range, would be really nice 😃 

(With the intent of offering a PR if I got it to work)

**Comment by jeremy-rifkin** [comment]
I think expression decomposition isn't possible in C (unless there's some wild new metaprogramming tool that's been added in C23 :P). Expression decomposition is one of the biggest parts of libassert but I think a C libassert.h that does everything other than expression decomposition is probably doable. Probably within the 2-8 hour range too, thanks so much for your interest in the library and contributing too the library!

**Comment by GavinRay97** [comment]
Ahh okay (I will have to google what `expression decomposition` is, ha)
Let me see if I can port this, if I get anything working I'll let you know =)

> thanks so much for your interest in the library and contributing too the library!

No problem! The only way to stay half-sane programming in C++ (IMO) is to:
- Pepper your code with assertions/contracts and use `libassert` to get actually useful info out of them.
- Turn on every friggin sanitizer and warning
	- For clang, something like `-Wall -Wextra -Wpedantic -Wnon-gcc -Wthread-safety -Wthread-safety-beta -fsanitize=address,leak,undefined -fsanitize-address-use-after-scope`

---

I'm not sure if you're familiar with the D programming language, but it has Contract-Driven Development built in that's absolutely stellar. You can write `in`, `out` and `invariant` assertions in both functions AND in classes/structs.
- https://dlang.org/articles/cppcontracts.html#contract-programming-d

So it's possible to write something like the below.
I'd love to be able to have this ability in C++, really wish it had `invariant` states for structs/classes.

```d
// template<class T>
class Deque(T)
{
	T[] data;
	size_t front;
	size_t back;
	size_t capacity;

	this(size_t capacity)
	{
		this.data = new T[capacity];
		this.front = 0;
		this.back = 0;
		this.capacity = capacity;
	}

	// These invariants are checked and upheld after every operation or mutation to the state of the deque.
	invariant
	{
		assert(this.front < this.capacity, "front index out of bounds");
		assert(this.back < this.capacity, "back index out of bounds");
		assert(this.front <= this.back, "front index is greater than back index");
		assert(this.back - this.front <= this.capacity; "back index is greater than front index by more than the capacity");

		// Check that all elements outside of the range [front, back) are null.
		foreach (i; 0 .. this.capacity)
		{
			if (i < this.front || i >= this.back)
			{
				assert(this.data[i] is null, "data at index " ~ i ~ " is not null");
			}
		}

		// If the deque is empty, then both front and back should be equal.
		if (this.front == this.back)
		{
			assert(this.data[this.front] is null, "front index is not null");
		}
		// If the deque is not empty, then both front and back should be non-null.
		else
		{
			assert(this.data[this.front]!is null, "non-empty deque: front index is null");
			assert(this.data[this.back - 1]!is null, "non-empty deque: back index is null");
		}
	}

	bool empty()
	{
		return this.front == this.back;
	}

	bool full()
	{
		return (this.back + 1) % this.capacity == this.front;
	}

	void push_back(T value)
	in (!this.full, "Deque is full!")
	{
		this.data[this.back] = value;
		this.back = (this.back + 1) % this.capacity;
	}

	T pop_front()
	in (!this.empty, "Deque is empty!")
	in (this.front < this.capacity, "front is out of bounds!")
	{
		T value = this.data[this.front];
		this.front = (this.front + 1) % this.capacity;
		return value;
	}
}
```

(Gonna close this issue for now, unless you want to re-open it to keep it for tracking?)
