### ISSUE TITLE
UB if you don't have addr2line: forked child exits with exit() instead of _exit

### ISSUE THREAD

**Issue by thiagomacieira** [jeremy-rifkin/libassert#42]
In https://github.com/jeremy-rifkin/libassert/blob/9bd1faa21448953021b54cebce77862be5444b7e/src/assert.cpp#L789-L794

That's wrong. You must use `_exit` so the child process won't try to run the `atexit` handlers, which includes all destructors.

**Comment by jeremy-rifkin** [comment]
Thank you so much for reporting this and looking into this. Sorry it's taken so long for me to respond! I'm fixing it in https://github.com/jeremy-rifkin/cpptrace which will shortly replace the tracing done here.

**Comment by jeremy-rifkin** [comment]
Resolved with #50
