### ISSUE TITLE
-Wuseless-cast warning in ASSERT with GCC 13

### ISSUE THREAD

**Issue by Morwenn** [jeremy-rifkin/libassert#49]
I got the following `-Wuesless-cast` warning with GCC 13:

```
In file included from cpp-sort/include/cpp-sort/detail/splaysort.h:21,
                 from cpp-sort/include/cpp-sort/sorters/splay_sorter.h:21,
                 from cpp-sort/include/cpp-sort/sorters.h:33,
                 from cpp-sort\examples\readme_example.cpp:11:
cpp-sort/include/cpp-sort/detail/splaysort.h: In member function 'void cppsort::detail::splay_tree_base::splay(cppsort::detail::binary_tree_node_base*)':
libassert-src/include/assert.hpp:1253:45: warning: useless cast to type 'struct libassert::detail::expression_decomposer<cppsort::detail::binary_tree_node_base*&, cppsort::detail::binary_tree_node_base*, libassert::detail::ops::neq>' [-Wuseless-cast]
 1253 |                          libassert::detail::expression_decomposer(libassert::detail::expression_decomposer{} << expr); \
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libassert-src/include/assert.hpp:1171:53: note: in definition of macro 'LIBASSERT_STMTEXPR'
 1171 |  #define LIBASSERT_STMTEXPR(B, R) (__extension__ ({ B R }))
      |                                                     ^
libassert-src/include/assert.hpp:1293:28: note: in expansion of macro 'ASSERT_INVOKE'
 1293 |  #define ASSERT(expr, ...) ASSERT_INVOKE(expr, true, true, "ASSERT", assertion, , __VA_ARGS__)
      |                            ^~~~~~~~~~~~~
cpp-sort/include/cpp-sort/detail/splaysort.h:80:17: note: in expansion of macro 'ASSERT'
   80 |                 ASSERT(parent != &sentinel_node_);
```

It occurred while comparing variables of pointer type. I am still trying to produce a minimum viable example to narrow it down.

**Comment by Morwenn** [comment]
I couldn't reproduce the issue with a fresh project, but by removing code from the project where I get the issue, I managed to reduce it down to the following snippet:

```cpp
#include <assert.hpp>

int main()
{
    int a, b;
    ASSERT(a != b);
}
```

At this point it is clear that it can trigger for most uses of `ASSERT`. I am now gonna explore the CMakeLists.txt used to build the library to understand what configuration sufficient and necessary to trigger the warning.

**Comment by Morwenn** [comment]
All I need to reproduce the warning with the code above is to call CMake with `-DASSERT_DECOMPOSE_BINARY_LOGICAL=ON` and to enable `-Wuseless-cast`.

Which gives the following warning:

```
In file included from test.cpp:1:
test.cpp: In function 'int main()':
assert.hpp:1253:45: warning: useless cast to type 'struct libassert::detail::expression_decomposer<int&, int&, libassert::detail::ops::neq>' [-Wuseless-cast]
 1253 |                          libassert::detail::expression_decomposer(libassert::detail::expression_decomposer{} << expr); \
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
assert.hpp:1171:53: note: in definition of macro 'LIBASSERT_STMTEXPR'
 1171 |  #define LIBASSERT_STMTEXPR(B, R) (__extension__ ({ B R }))
      |                                                     ^
assert.hpp:1293:28: note: in expansion of macro 'ASSERT_INVOKE'
 1293 |  #define ASSERT(expr, ...) ASSERT_INVOKE(expr, true, true, "ASSERT", assertion, , __VA_ARGS__)
      |                            ^~~~~~~~~~~~~
test.cpp:6:5: note: in expansion of macro 'ASSERT'
    6 |     ASSERT(a != b);
      |     ^~~~~~
```

**Comment by jeremy-rifkin** [comment]
Thank you, confirmed. https://godbolt.org/z/n8K1aGK65.
I'll probably add a pragma to ignore that warning. I'm realizing the `#pragma GCC diagnostic ignored "-Wparentheses"` inserted by the macro may be disabling that warning for the rest of any file that uses an assert, I'll try to address that too.

**Comment by jeremy-rifkin** [comment]
Or you may beat me to it :)

**Comment by Morwenn** [comment]
Not really, I tried something locally that seemed to work, but apparently it creates other issues :eyes:

**Comment by jeremy-rifkin** [comment]
Interesting, I wonder if a deduction guide is needed? I'm maybe a little more inclined to just use a pragma - the expression decomposition and assert invocation code has ended up being intricate, partly due to workarounds for compiler bugs, and I'm a little scared to touch it.

**Comment by Morwenn** [comment]
Don't hesitate to replace my proposed fix with a pragma. To be honest I'm kind of surprised that my suggestion hits an error but the existing code does not 😅

**Comment by jeremy-rifkin** [comment]
It looks like what I'm trying is also introducing new unexpected errors. Gremlins.
