### ISSUE TITLE
Odd -Wnonnull-compare warning when enabling expression decomposition

### ISSUE THREAD

**Issue by Morwenn** [jeremy-rifkin/libassert#53]
While compiling my project with `-DASSERT_DECOMPOSE_BINARY_LOGICAL=ON` with MinGW-w64 GCC 13 I got several occurrences of the following warning:

```
In file included from cpp-sort/include/cpp-sort/detail/config.h:72,
                 from [...]:
libassert-src/include/assert.hpp: In member function 'constexpr decltype(auto) libassert::detail::ops::land::operator()(A&&, B&&) const [with A = bool&; B = const char (&)[50]]':
libassert-src/include/assert.hpp:295:47: warning: 'nonnull' argument 'rhs' compared to NULL [-Wnonnull-compare]
  295 |          LIBASSERT_GEN_OP_BOILERPLATE(land,   &&);
      |                                               ^
libassert-src/include/assert.hpp:268:45: note: in definition of macro 'LIBASSERT_GEN_OP_BOILERPLATE'
  268 |                 return std::forward<A>(lhs) op std::forward<B>(rhs); \
      |   
```

It appears in a lot of translation units that happen to include `<assert.hpp>` (unsure whether it comes from use or include alone), and ultimately it doesn't feel like it comes from my own code directly. The line in the `config.h` above is just `#include <assert.hpp>`. The warning points to the following part of the code:

```cpp
#ifdef ASSERT_DECOMPOSE_BINARY_LOGICAL
 LIBASSERT_GEN_OP_BOILERPLATE(land,   &&);
 LIBASSERT_GEN_OP_BOILERPLATE(lor,    ||);
#endif
```

I haven't managed to produce an MRE yet and can't totally rule out the fact that it might still come from my own code.

**Comment by jeremy-rifkin** [comment]
I can reproduce! https://godbolt.org/z/KW51jhcqe
I tried a bunch of stuff without any luck, then I added an optimization flag and it reproduced 😅

**Comment by jeremy-rifkin** [comment]
I don't think this error should come from any libassert code alone. Do you have the lowercase `assert` alias turned on by chance?

**Comment by Morwenn** [comment]
No, I'm not interested in the lowercase macro, so I haven't enabled the option.

**Comment by Morwenn** [comment]
I think I found the culprit in the timsort implementation:

```cpp
CPPSORT_ASSERT(len2 != 0 && "comparison function violates its general contract");
```

The number of characters matches the one mentioned in the error.

**Comment by Morwenn** [comment]
To give an idea of how I did things, the `CPPSORT_ASSERT` macro is basically implemented as:

```cpp
#if defined(CPPSORT_USE_LIBASSERT)
#    define CPPSORT_ASSERT(...) ASSERT(__VA_ARGS__)
#else
#    define CPPSORT_ASSERT(...) assert((__VA_ARGS__))
#endif
```

I guess that I will have to turn that into something along the lines of:

```cpp
#if defined(CPPSORT_USE_LIBASSERT)
#    define CPPSORT_ASSERT(condition, message, ...) ASSERT(condition, message, __VA_ARGS___)
#else
#    define CPPSORT_ASSERT(condition, message, ...) assert(condition && message)
#endif
```

I lose the nice property of being able to pass expressions along the lines of `foo<A, B>(5)` to the condition and have it just work, but I don't think there's a way to get the both of best world there.

Also fun fact, prepending a unary + to the string literal silences the warning:

```cpp
int main() {
    bool b = true;
    ASSERT(b && +"foo");
}
```

I don't know whether anything should or could be done on the libassert side.

**Comment by jeremy-rifkin** [comment]
Thank you! Interesting issue. `ASSERT(b && +"foo");` is a good trick.

I think it is possible to do stuff on the libassert side. I think an `if constexpr` could be used in `libassert::detail::ops::land::operator()` to suppress the non-null warning when B is a string literal. In principle it's better to pass the message separately but this is a common pattern so it may be reasonable to go a little extra distance to support it.

**Comment by Morwenn** [comment]
I see how it would be possible, though I'm unsure how valuable it is and how many subtle issues it can cause. That said it would fully make `ASSERT` a drop-in replacement for people like me who only intend to use libassert as an opt-in for additional diagnostics.

I guess the other solution would be to give a "recipe" in the documentation to do what I did above - I might be wrong, but I doubt I'm the only one who would try to use it as an opt-in replacement for `assert` like that 😛
