### ISSUE TITLE
-Wunknown-warning-option warning with Clang 14

### ISSUE THREAD

**Issue by Morwenn** [jeremy-rifkin/libassert#60]
I get the following `-Wunknown-warning-option` warnings when building the library with Clang 14 on WSL2 without any specific CMake option enabled, building libassert v1.2:

```
warning: unknown warning option '-Wuseless-cast' [-Wunknown-warning-option]
warning: unknown warning option '-Wnonnull-compare' [-Wunknown-warning-option]
```

Wherever they are added, you probably want to restrict them to GCC builds.

**Comment by jeremy-rifkin** [comment]
Thank you! Should be a quick fix.
