### ISSUE TITLE
not working with cmake fetch content 

### ISSUE THREAD

**Issue by sanjuchopracool** [jeremy-rifkin/libassert#62]
I always getting this error

CMake Error at C:/Qt/Tools/CMake_64/share/cmake-3.24/Modules/FetchContent.cmake:1182 (message):
  No content details recorded for assert
Call Stack (most recent call first):
  C:/Qt/Tools/CMake_64/share/cmake-3.24/Modules/FetchContent.cmake:1665 (__FetchContent_getSavedDetails)
  C:/Qt/Tools/CMake_64/share/cmake-3.24/Modules/FetchContent.cmake:1958 (FetchContent_Populate)
  CMakeLists.txt:9 (FetchContent_MakeAvailable)

CMakeLists.txt and main.cpp are same as mentioned in readme

**Comment by jeremy-rifkin** [comment]
Thank you for the report. I can reproduce, I'm unsure when things broke.

**Comment by jeremy-rifkin** [comment]
It was a silly mistake, I've updated the docs
```diff
FetchContent_Declare(
-   libassert
+   assert
    GIT_REPOSITORY "https://github.com/jeremy-rifkin/libassert"
    GIT_TAG "v1.2"
)
FetchContent_MakeAvailable(assert)
```

Sorry for the inconvenience!
