### ISSUE TITLE
Stringification customization

### ISSUE THREAD

**Issue by huangqinjin** [jeremy-rifkin/libassert#84]
There are several problems in current implementation, e.g., not allow to override default stringification, customization on enum and pointer does not work.

```c++
#if 1
template<> struct libassert::stringifier<int> {
    std::string stringify(int x) {
        return "this is a int " + std::to_string(x);
    }
};

template<> struct libassert::stringifier<int*> {
    std::string stringify(int*) {
        return "this is a int* ";
    }
};

template<> struct libassert::stringifier<std::errc> {
    std::string stringify(std::errc ec) {
        return libassert::detail::stringification::stringify(std::error_condition(ec));
    }
};
#endif

int main() {
    int x = 0;
    ASSERT(x, &x, std::errc{});
}
#endif
```

The above code outputs
```
    Where:
        x => 0
    Extra diagnostics:
        &x          => <instance of int*>
        std::errc{} => <instance of std::errc>
```

Current stringification relies on complicated and verbose and error-prone SFINAE.
Since we are using C++17 now, `if constexpr` can reduce the use of SFINAE.

**Comment by jeremy-rifkin** [comment]
Thanks for opening this. The current system is definitely in need of work. It used to be implemented with a long if-constexpr chain and I think you’re right that it may be time to move back to that.

**Comment by jeremy-rifkin** [comment]
I'm going to close this, happy to discuss improvements further. I think there is likely still room for improvement.
